name: Build Kitsas Windows
on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Qt
        uses: jurplel/install-qt-action@v3
        with:
          version: '5.15.2' # Stabiili versio, joka toimii Kitsaan kanssa
          host: 'windows'
          target: 'desktop'
          arch: 'win64_mingw81'

      - name: Build
        shell: cmd
        run: |
          mkdir build
          cd build
          qmake ../kitsas/kitsas.pro "CONFIG += release"
          mingw32-make -j 2

      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: Kitsas-Windows-Portable
          path: build/release/kitsas.exe
